### ISSUE TITLE
Not passing silent param to 'find' function

### ISSUE THREAD

**Issue by billbo99** [theRustyKnife/rusty-locale#2]
https://github.com/theRustyKnife/rusty-locale/blob/a276811651183f5635737c5941b72f5077defdfc/rusty-locale/icons.lua#L47

**Comment by theRustyKnife** [comment]
Hmm, not sure whether I want to do that - a non-existent prototype is different from a prototype with invalid icons... You can get around that by doing `icons.of(prototypes.find(name, type, true))`, which *is* more verbose, but it's clear what exactly you're silencing. Maybe a note mentioning this in the docs would be a better solution?

**Comment by theRustyKnife** [comment]
Actually, there's still an issue with what I suggested: The function doesn't expect the prototype to be nil at all... I could just add a check for that, but I wanna see if I can find a better solution first.

**Comment by theRustyKnife** [comment]
Sorry I took so long, but this should be fixed by 7de11a8.
