### ISSUE TITLE
Issue with 1.0.0

### ISSUE THREAD

**Issue by dbiser99** [theRustyKnife/rusty-locale#5]
Not sure why it is disabling Transport Drones, but based on the error messages and the fact disabling your mod also fixes it...

![Rusty Locale Error](https://user-images.githubusercontent.com/68525988/90240648-a7cb4a80-ddf7-11ea-98aa-0ee839722fa8.png)

**Comment by ST-DDT** [comment]
See https://github.com/theRustyKnife/rusty-locale/pull/4
